### ISSUE TITLE
go get -u failed

### ISSUE THREAD

**Issue by lazytiger** [matcornic/subify#7]
when I run "go get -u github.com/matcornic/subify", I got error message as follows:

cd /home/hoping/programs/golang/path/src/github.com/matcornic/subify; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/google/go-querystring'
package github.com/matcornic/subify: exit status 128

**Comment by gonzaloserrano** [comment]
same here

**Comment by matcornic** [comment]
Should be fixed with 7fe8dd35cc2506bbe8890880fb9fbf52cb1d759d

**Comment by axelhzf** [comment]
I am having the problem. It looks like 7fe8dd3 does not fix the problem.

**Comment by matcornic** [comment]
@axelhzf sorry, could you retry ?

It seems that old vendor files were still managed with submodules (from Glide) after I migrated to dep.
I deleted the vendors and did a `dep init` to recreate the vendor from scratch.

**Comment by matcornic** [comment]
4da4d8282cfe026474fd6affb8c7d4525200fbab & 75fc032aa96bbd7b5d8d8a164176aa8487e98484
